/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package IGU;

/**
 *
 * @author angeg
 */
public class Worker extends javax.swing.JPanel {

    /**
     * Creates new form Trabajador
     */
    public Worker() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

         botones = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Op4 = new javax.swing.JRadioButton();
        Op1 = new javax.swing.JRadioButton();
        Op3 = new javax.swing.JRadioButton();
        Op2 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 2, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("¿Que desea reservar?");

        Op4.setForeground(new java.awt.Color(0, 0, 0));
        Op4.setText("Cine");
        Op4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Op4ActionPerformed(evt);
            }
        });

        Op1.setForeground(new java.awt.Color(0, 0, 0));
        Op1.setText("Gimnasio");
        Op1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Op1ActionPerformed(evt);
            }
        });

        Op3.setForeground(new java.awt.Color(0, 0, 0));
        Op3.setText("Yoga y Baile");
        Op3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Op3ActionPerformed(evt);
            }
        });

        Op2.setForeground(new java.awt.Color(0, 0, 0));
        Op2.setText("Barista");
        Op2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Op2ActionPerformed(evt);
            }
        });

        jButton1.setText("Salir");

        jButton2.setText("Siguiente");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Op1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Op2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Op3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Op4, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jButton1)
                        .addGap(63, 63, 63)
                        .addComponent(jButton2)))
                .addContainerGap(109, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(Op1)
                .addGap(18, 18, 18)
                .addComponent(Op2)
                .addGap(18, 18, 18)
                .addComponent(Op3)
                .addGap(18, 18, 18)
                .addComponent(Op4)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    private void Op4ActionPerformed(java.awt.event.ActionEvent evt) {                                    
        
    }                                   

    private void Op2ActionPerformed(java.awt.event.ActionEvent evt) {                                    
       
    }                                   

    private void Op1ActionPerformed(java.awt.event.ActionEvent evt) {                                    
     

    }                                   

    private void Op3ActionPerformed(java.awt.event.ActionEvent evt) {                                    
        
    }                                   

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
       //Creacion de las diferentes pantallas
        
        
        Gimnasio gym = new Gimnasio();
        Barista cafe = new Barista();
        Baile clase1 = new Baile();
        Cine sala = new Cine();
        
        
        //agrupacion de los botones
        botones.add(Op1);
        botones.add(Op3);
        botones.add(Op2);
        botones.add(Op4);
        if (Op1.isSelected()) {
            gym.setVisible(true);

            this.dispose();

            gym.setLocationRelativeTo(null);

        } else if (Op2.isSelected()) {
            cafe.setVisible(true);

            this.dispose();

            cafe.setLocationRelativeTo(null);

        } else if (Op3.isSelected()) {
            clase1.setVisible(true);

            this.dispose();

            clase1.setLocationRelativeTo(null);

        } else if (Op4.isSelected()) {
            sala.setVisible(true);

            this.dispose();
            
            sala.setLocationRelativeTo(null);

        }
    }                                        


    // Variables declaration - do not modify                     
    private javax.swing.JRadioButton Op1;
    private javax.swing.JRadioButton Op2;
    private javax.swing.JRadioButton Op3;
    private javax.swing.JRadioButton Op4;
    private javax.swing.ButtonGroup botones;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration                       
}

      
