/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package IGU;

import javax.swing.ButtonGroup;

/**
 *
 * @author angeg
 */
public class Gimnasio extends javax.swing.JFrame {
    

    /**
     * Creates new form Gimnasio
     */
    public Gimnasio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botones = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        bSee = new javax.swing.JRadioButton();
        bDo = new javax.swing.JRadioButton();
        bChange = new javax.swing.JRadioButton();
        bDelete = new javax.swing.JRadioButton();
        bAtras = new javax.swing.JButton();
        BNext = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("¿Que desea hacer?");

        bSee.setForeground(new java.awt.Color(0, 0, 0));
        bSee.setText("Ver reservaciones");
        bSee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSeeActionPerformed(evt);
            }
        });

        bDo.setForeground(new java.awt.Color(0, 0, 0));
        bDo.setText("Hacer reservaciones");

        bChange.setForeground(new java.awt.Color(0, 0, 0));
        bChange.setText("Cambiar reservaciones");

        bDelete.setForeground(new java.awt.Color(0, 0, 0));
        bDelete.setText("Eliminar reservaciones");

        bAtras.setText("Atras");
        bAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAtrasActionPerformed(evt);
            }
        });

        BNext.setText("Siguiente");
        BNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BNextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(bAtras)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                .addComponent(BNext)
                .addGap(79, 79, 79))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bDo)
                            .addComponent(bSee)
                            .addComponent(bChange)
                            .addComponent(bDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(bSee)
                .addGap(18, 18, 18)
                .addComponent(bDo)
                .addGap(18, 18, 18)
                .addComponent(bChange)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bDelete)
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bAtras)
                    .addComponent(BNext))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bSeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bSeeActionPerformed

    private void BNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BNextActionPerformed
  
        botones.add(bSee);
        botones.add(bDo);
        botones.add(bChange);
        botones.add(bDelete);

        Trabajador menu = new Trabajador();
        DatosGym datos = new DatosGym();
        proyectofinal.grupo2.Gimnasio gim = new proyectofinal.grupo2.Gimnasio();
        proyectofinal.grupo2.Trabajador trabajador1[] = new proyectofinal.grupo2.Trabajador[30];
        trabajador1[0] = new proyectofinal.grupo2.Trabajador("Mike", "It", "1");
        trabajador1[1] = new proyectofinal.grupo2.Trabajador("Juan", "It", "2");
        trabajador1[2] = new proyectofinal.grupo2.Trabajador("Hernest", "It", "3");
        trabajador1[3] = new proyectofinal.grupo2.Trabajador("Sofia", "It", "4");
        trabajador1[4] = new proyectofinal.grupo2.Trabajador("Juliana", "It", "5");
        trabajador1[5] = new proyectofinal.grupo2.Trabajador("Fernanda", "It", "6");
        trabajador1[6] = new proyectofinal.grupo2.Trabajador("Bravo", "It", "7");

        if (bSee.isSelected()) {

        datos.setVisible(true);
        this.dispose();
        datos.setLocationRelativeTo(null);
           

        } else if (bDo.isSelected()) {
            datos.setVisible(true);
        this.dispose();
        datos.setLocationRelativeTo(null);
           

    
            

        } else if (bChange.isSelected()) {
            datos.setVisible(true);
        this.dispose();
        datos.setLocationRelativeTo(null);
           

           
             

        } else if (bDelete.isSelected()) {
            datos.setVisible(true);
        this.dispose();
        datos.setLocationRelativeTo(null);
           

            
           

        }
    }//GEN-LAST:event_BNextActionPerformed

    private void bAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAtrasActionPerformed
        Trabajador menu =new Trabajador();
        menu.setVisible(true);
        this.dispose();
        menu.setLocationRelativeTo(null);
        
    }//GEN-LAST:event_bAtrasActionPerformed

  

    public ButtonGroup getBotones() {
        return botones;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BNext;
    private javax.swing.JButton bAtras;
    private javax.swing.JRadioButton bChange;
    private javax.swing.JRadioButton bDelete;
    private javax.swing.JRadioButton bDo;
    private javax.swing.JRadioButton bSee;
    private javax.swing.ButtonGroup botones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
